In [2]:
import numpy as np    # it is an unofficial standard to use np for numpy
import time

数组和向量的创建

In [ ]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}") #创建0数组，()是数组长度；shape输出维度，单元素元组会有逗号
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}") #同上，只不过显式指定了长度为4的一维数组
#在np模组中调用子模块random，random_sample()生成[0,1)随机数，形状 =1行(4个元素)；rand生成随机(0,1)均匀分布；randn()生成随机(0,1)正态分布
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}") 
#shape[0]：即第1个参数——行数;shape[1]：即第2个参数——列数;shape[-1]：即倒数第1个参数——列数;shape[-2]：即倒数第2个参数——行数
#一维时，shape[0]指的是特征数量

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.82265055 0.76971832 0.73604289 0.09635863], a shape = (4,), a data type = float64


In [4]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
#创建等差数列数组，numpy.arange([start,] stop[, step])；起始值（默认0）；结束值；步长（默认1）
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}") 
# 生成(0,1)均匀分布随机数，形状 = 1行(4个元素)
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.49384898 0.21762998 0.17046452 0.85247724], a shape = (4,), a data type = float64


In [5]:
# NumPy routines which allocate memory and fill with user specified values；创建指定的数组
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


操作向量:索引

In [6]:
#vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

#access an element；标量值没有shape（维度）属性，输出为空，只有Numpy数组才有
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")
print(f"a.shape:{a.shape}")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a.shape:(10,)
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


操作向量:切片

In [7]:
#vector slicing operations
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


操作向量:单向量操作

In [8]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a 
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


操作向量:向量运算

In [9]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


In [10]:
#try a mismatched vector operation；向量必须要有相同的行列数
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


In [11]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


操作向量:点积

In [12]:
def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [13]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


In [14]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")

NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


In [15]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ") #Numpy计算更快

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 28.4519 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 2186.0461 ms 


In [16]:
# show common Course 1 example
X = np.array([[1],[2],[3],[4]]) #生成4x1矩阵
w = np.array([2])
c = np.dot(X[1], w)

print(f"{X[0]}")#单行索引会降维，这里输出的是第一行
print(f"X[1] has shape {X[1].shape}")

print(f"w has shape {w.shape}")

print(c)
print(f"c has shape {c.shape}")

[1]
X[1] has shape (1,)
w has shape (1,)
4
c has shape ()


矩阵创建

In [17]:
a = np.zeros((1, 5))    #创建一行五列的0数组                                   
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))    # 创建一行一列的的二维数组（随机浮点数）（虽然只有一个元素，但结构仍是二维数组（非标量））
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]


In [18]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


操作矩阵：索引

In [19]:
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices reshape函数将其转换为(x,y)的矩阵；-1为自动计算（这里为行数）
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n") #访问3行1列元素

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


操作矩阵：切片

In [20]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array


Numpy设置输出格式

In [21]:
import numpy as np
np.set_printoptions(precision=4, suppress=True) #precision=4显示4位小数，suppress=True禁用科学计数法，避免小数值显示为0

x = np.array([1.23456789])
print(x)  # 输出：[1.235]

[1.2346]


Numpy计算

In [22]:
import numpy as np
X = np.array([[1, 2], [3, 4]])  # 2x2 矩阵
mu = 2.5  # 标量
sigma = 1.5  # 标量
X_norm = (X - mu) / sigma
X_norm

array([[-1.    , -0.3333],
       [ 0.3333,  1.    ]])


np.c_和np.r_的用法解析


In [ ]:
# 一维数组情况:如果A和B都是一维数组 → 转换为列向量后水平拼接
z_tmp = np.array([1, 2, 3])  # 形状 (3,)
y = np.array([4, 5, 6])      # 形状 (3,)
np.c_[z_tmp, y]  # 输出 [[1,4], [2,5], [3,6]] 形状 (3,2)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# 二维数组情况:如果A和B都是二维数组 → 直接水平拼接
a = np.array([[1, 2, 3],[7,8,9]])  # 形状 (2, 3)
b = np.array([[4,5,6],[1,2,3]])    # 形状 (2, 3)
a,b 


(array([[1, 2, 3],
        [7, 8, 9]]),
 array([[4, 5, 6],
        [1, 2, 3]]))

In [ ]:
f=np.c_[a,b] #按列连接两个矩阵，就是把两矩阵左右相加，要求行数相等。  形状 (2, 6)
f

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 1, 2, 3]])

In [ ]:
f=np.r_[a,b] #按行连接两个矩阵，就是把两矩阵上下相加，要求列数相等。
f

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

布尔索引

In [26]:
import numpy as np

# 特征值 (x)
x_train = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6])

# 标签值 (y)
y_train = np.array([0, 1, 0, 1, 1, 0])

In [27]:
pos = y_train == 1  # [False, True, False, True, True]
selected_x = x_train[pos]
print(selected_x)   #- `x_train[pos]` 将返回 `x_train` 中索引为1、3、4的元素（因为`pos`在索引1、3、4处为True）：

[2.2 4.4 5.5]
